application: kanji-z-hrd
version: 3
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /shared
  static_dir: shared

- url: /lists
  static_dir: lists


- url: /kanjitest(/.*)?
  script: kanjitest.app

- url: /test/
  static_dir: test


- url: /kanjilist(/.*)?
  script: uberlist.app

- url: /uberlist/
  static_dir: uberlist


- url: /kanjiwarp
  script: warp.py
  login: admin

- url: /kanjiwarp/
  script: warp.py
  login: admin

- url: /kanjiwarp/index\.html
  script: warp.py
  login: admin

- url: /warp/
  static_dir: warp
  login: admin

- url: /kanjiquiz
  script: quiz.py

- url: /kanjiquiz/
  script: quiz.py

- url: /kanjiquiz/index\.html
  script: quiz.py

- url: /quiz/
  static_dir: quiz

- url: /kanjiflip(/.*)?
  script: kanjiflip.app

- url: /flip/
  static_dir: flip

- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6